### ISSUE TITLE
Error on enabling plugin in Blender 2.8

### ISSUE THREAD

**Issue by tazuras** [charliebanks/nms-base-builder#14]
When I try to enable the plugin I recieve an error message and am unable to enable it.  Here is the message:

![image](https://user-images.githubusercontent.com/36608253/64209944-e3cc0080-ce6f-11e9-94b6-f4c9574d8ae0.png)

Hopefully, I am not doing something wrong :D

**Comment by charliebanks** [comment]
oops! You're right. I did a silly thing. I've just re-uploaded the file to
github and nexus. If you can re-download and try again it should work

thanks

**Comment by tazuras** [comment]
That seems to have done it, thanks so much!
