### ISSUE TITLE
Material Changes Made In Blender Not Making It To Game

### ISSUE THREAD

**Issue by ukmerlin** [charliebanks/nms-base-builder#19]
Pretty confident that when I make material changes to the scene in Blender they never make it to the game.

**Comment by ukmerlin** [comment]
[SpaceStationv6.zip](https://github.com/charliebanks/nms-base-builder/files/3682893/SpaceStationv6.zip)

**Comment by bisdat** [comment]
First off thanks @charliebanks for the great plugin - it has transformed NMS base building!

@ukmerlin I loaded up your "double doughnut" and imported into the game - it looks fantastic, but aside from the mini teleporters needing connecting all seems to be exactly as the blender save file. What changes are not making it to the game?

**Comment by ukmerlin** [comment]
Everything has always been connected although many of the landing pad lights will not work but that is a NMS wiring issue all around. Not really intending to share the platform at least yet but Charlie had asked to see it to help.  

As this ticket mentions, the specific problem is that if I make mass material changes to the items they do not come across to the game, for example most of the antenna colouring never makes it to the game. I do not think any Blender colouring has ever made it over, I end up having to colour in game.  

Seperate from this ticket I find that due to bases being uploaded and perhaps out of sync with actual ongoing construction there are issues with parts either having collision that should not, or not having collision that should. So for example climbing some stairs will result in suddenly falling thru them.

**Comment by ukmerlin** [comment]
By the way in VR this is awesomely huge!!! And worth a visit in the system. I have not yet successfully got this to go onto a better planet.

**Comment by charliebanks** [comment]
Hi @ukmerlin , thanks for attaching the file. I had a quick look.

1. I can see you've applied the material. But I noticed that the UserData attribute was not reflective of this (this is where the actual colour value is stored for NMS to read). Did you apply the material via typical Blender methods? Or did you apply it via the NMS UI Panel? Applying through the NMS panel will apply the material but will also ensure that the UserData value is set properly.

**Comment by charliebanks** [comment]
Also thanks @bisdat  for jumping in and taking a look, I'm glad you're enjoying the plugin :)

**Comment by ukmerlin** [comment]
Dohhh! I feel like such a plugin :) I always kept that box twirled away.
Regarding the collision issues will let you know once the update drops.

**Comment by charliebanks** [comment]
Haha no worries. What I can do is have a fall back that will check the material if the UserData is not set properly. That way you could potentially apply materials using usual Blender ways. 

This would still rely on those NMS materials being present/imported though (i.e you can't just apply any red material and it will work!)
