### ISSUE TITLE
Cube Object Snapping

### ISSUE THREAD

**Issue by ukmerlin** [charliebanks/nms-base-builder#20]
Objects from the Cube group will not snap to cube objects and cannot be adjusted thru the source target previous next snap buttons.

**Comment by charliebanks** [comment]
Thanks @ukmerlin , I will ensure the next release has some improve snapping for the cube parts. :)

**Comment by charliebanks** [comment]
1.1.4 release has some improved snapping fixes for cubes, such as the stairs. Let me know if there's anything else.

**Comment by ukmerlin** [comment]
Many thanks :)
