### ISSUE TITLE
Curved Glass Cube Roof Causes Infinite Length Wire Connector

### ISSUE THREAD

**Issue by ukmerlin** [charliebanks/nms-base-builder#21]
If a cube roof with curve is added to a building its internal wiring connector becomes infinitely long.

**Comment by charliebanks** [comment]
Can you attach a blender file please.

**Comment by ukmerlin** [comment]
OK it will be a while, I deleted the objects to get rid of the problem but I might still have a base that does it. If not I will drop some back in.

**Comment by charliebanks** [comment]
Closing this as I haven't been able to reproduce this. Feel free to re-open the issue if you run into this again and can provide a step by step or blender file :)
