### ISSUE TITLE
MiniTeleport Location Wire

### ISSUE THREAD

**Issue by ukmerlin** [charliebanks/nms-base-builder#22]
Hi,
so it is not currently possible to add teleport location wiring. This would be useful as the game has a range limit on what it will let you connect to.

**Comment by ukmerlin** [comment]
Any chance this could be fixed? Have a really good present application for this ability in Blender. Ta! :)

**Comment by charliebanks** [comment]
The other wires can be found as base parts. I think it's called Portal
Wire, try searching for it in the list.

When you make one it will create it with the lightning controls ok both
sides.

I admit I can make it a bit easier to make one, like the standard cables.

Let me know how that goes.

**Comment by ukmerlin** [comment]
I had just tried it again now which is what prompted the request.
So to be clear you shift select the two portals, then click on the Portal Line Button under technology since it is not under power and wiring.
It does not appear to do anything. When I originally wrote it up it had the same effect as the power wiring, it would link both thru the power port only. Now it looks like nothing. ~ S

**Comment by charliebanks** [comment]
Ah , ok, if you build one without selecting it should create a wire at the
center of the scene, then you can drag the points where they need to go.
