### ISSUE TITLE
Feature request: Add Freighter parts

### ISSUE THREAD

**Issue by Devilin-Pixy** [charliebanks/nms-base-builder#23]
Love your tool! But, I would love to be able to design my Freighter as well. A freighter is considered to be a base, so it loads fine. It is just a bit harder to design currently, as there are no models included for freighter building parts.

One thing I noticed is that there will be a few parts present by default, even if not specified in the save data. It is also possible to build beyond the confines of the freighter build area, although 'outside' is no longer protected (no breathable air in space).

I have yet to figure out what exactly happens when creating multiple bases marked as freighter base ("BaseType":{"PersistentBaseTypes":"FreighterBase"}). It does appear they are being ignored, but not sure.

If you would/could be so kind to add all the models for freighter building parts, I would truly appreciate it. This would certainly allow for some really creative freighter builds. Might be worth exploring additional possibilities as well.

Keep up the good work!

**Comment by charliebanks** [comment]
I've just uploaded 1.1.4 which added Freighter support. Let me know how it goes! :)
