### ISSUE TITLE
Gaps in build parts

### ISSUE THREAD

**Issue by ukmerlin** [charliebanks/nms-base-builder#24]
Since the latest update any metal (and presumably concrete / wood) parts are left with a gap in between. Some parts seem to be stripped of detail as well, such as the metal panel with window and door which become very primitive renderings in game.

**Comment by charliebanks** [comment]
1.Do you have any scaling attributes on the parts you have in Blender?

2. The tool should not affect anything like rendering in the game, it literally is just giving you a description of where parts need to be placed. What you're describing sounds like a LOD issue in-game. Which can usually appear if you have lots and lots of items.

3. Please attach a blender file, it's always a lot easier for me if I have something to look at.

**Comment by ukmerlin** [comment]
Thought I had answered this; None of the parts in question are scaled. The file I put on google docs as it is too big.

**Comment by charliebanks** [comment]
If you upload something to google drive, you'll need to paste the link to it here :)

**Comment by ukmerlin** [comment]
But then my file is available to all!!
