### ISSUE TITLE
NMS objects not mirrored as expected

### ISSUE THREAD

**Issue by waldo3000** [charliebanks/nms-base-builder#26]
In a NMS Base Builder test, I created a bubble room in Blender, duplicated it, moved one copy to the side and mirrored in x to make two bubble rooms facing each other (see image).  In NMS, the second part appeared un-mirrored (see image).
![blender test](https://user-images.githubusercontent.com/10029447/69499651-ef9cf100-0eb9-11ea-9d6a-9a15c423bc5f.png)
![NMS test](https://user-images.githubusercontent.com/10029447/69499656-faf01c80-0eb9-11ea-8faa-e96114b3df79.png)

**Comment by charliebanks** [comment]
It's likely the mirror tool works on a component/vertex level. Is there a
way in blender to mirror the transform instead? The transform data is what
will need to be correct.

**Comment by charliebanks** [comment]
Scratch that - I see you did a scale -1 in the channels to do the mirror.
It's likely NMS isn't reading that correctly. NMS probably doesn't like
that :) you'll need to mirror it via the translation and rotation values
only. This is how I've set it up using the snapping features.

**Comment by waldo3000** [comment]
OK, no problem.  I can easily do a 180 rotation instead.  Just getting my feet wet on this after being inspired by the statue at the weekend event.

**Comment by charliebanks** [comment]
👍
