### ISSUE TITLE
Placing/Moving short walls breaks the export function

### ISSUE THREAD

**Issue by UmBottesWillen** [charliebanks/nms-base-builder#30]
(Concrete) short walls, both half and normal sized, appear to not have any snap points when adding them, making it necessary to move them manually afterwards. One of those two actions breaks the export function of your mod, resulting in an unusable save, if pasted into the NMS save file, all though in most cases the NMS save editor refuses to save the altered XML code anyways. From what I can tell, the last part of the save, containing the base's name, among other things, goes missing, all though pasting it in manually after the fact does not fix the issue.

Used Software:
NMS Base Builder 1.1.8
NMS Save editor 1.6.1.1
Blender v2.80.75
No Man's Sky 2.34

**Comment by charliebanks** [comment]
So there is two issues here.

1. Short walls don't have snap points. I probably overlooked them so you're correct there. I can try to and do a small update that fixes them.

2. I can't really see how the above point can affect the the import/export functionality. Are you able to tell me your exact steps? Bare in mind - you must Import a base before being able to export one. Importing it will make sure you have the base name, galactic address etc correctly stored in the blender tool. You can't just make things in blender and then export it as it won't have that information yet. Sorry if that wasn't clear.

**Comment by UmBottesWillen** [comment]
I am unfortunately unable to reproduce my steps, so there is in fact no link between the short wall representations not being feature-complete and the export function not working. I guess the issue arose on my part, because my base file covers more than 90k lines currently and I had problems using blender to work on my base. I was just thrown off because the exported XML code had a different structure to it that the one the game generates, all though the game seems to be able to interpret it all the same.

**Comment by charliebanks** [comment]
I've just release 1.1.9 which adds snapping points for those short walls and half short walls.

Feel free to open another issue if there's anything else.
