### ISSUE TITLE
Switch Byte Beat missing power connection and message setter.

### ISSUE THREAD

**Issue by Devilin-Pixy** [charliebanks/nms-base-builder#32]
The 'Switch Byte Beat' under the 'Power' header is missing a power connection on the opposite corner of the Byte Beat connection. Would be nice to see it added, to not have to connect in-game to then re-import into Blender again.

The 'Switch Byte Beat' is also missing a message setter similar to the Byte Beat, which defines your presets for this object. The 'Message' does not get imported, which is somewhat annoying.

**Comment by charliebanks** [comment]
fixed in 1.1.9
