### ISSUE TITLE
Triangles are the wrong shape and don't snap properly

### ISSUE THREAD

**Issue by instakibbs** [charliebanks/nms-base-builder#40]
The triangles aren't the right size and are spaced when translated to the game. Makes building with them impossible sadly.

**Comment by davebastian** [comment]
Related: triangles have a decided orientation/rotation. This may be too far out there, but it'd be nice to have some visual cue in Blender; as it is, I spend an inordinate amount of time switching back and forth between the game and Blender to get this right. (The same issue applies to small, square metal floor pieces.)

![triangle-pieces](https://user-images.githubusercontent.com/20446496/107221132-78754f00-69d0-11eb-8d4d-a02082f5e1c3.jpg)

![small-triangles](https://user-images.githubusercontent.com/20446496/107221200-8b881f00-69d0-11eb-937b-fe6609f4e3a5.jpg)

**Comment by charliebanks** [comment]
Addressed in 1.3.2 :)
