### ISSUE TITLE
Concrete/Wooden/Metal Roof not rendering properl

### ISSUE THREAD

**Issue by Novoca1n3** [charliebanks/nms-base-builder#43]
Roof imports into blender as something similar to a roof panel instead of a square with raised centre.
![Capture](https://user-images.githubusercontent.com/24946111/93395923-206f6c00-f8ba-11ea-8215-6d30f9b98631.JPG)
![Capture1](https://user-images.githubusercontent.com/24946111/93395928-21a09900-f8ba-11ea-9828-f73bc1e0463c.JPG)

**Comment by charliebanks** [comment]
Can you post a screenshot in NMS to what it should look like?

**Comment by Novoca1n3** [comment]
![20200917185202_1](https://user-images.githubusercontent.com/24946111/93448553-14fe5e00-f917-11ea-8a54-0abddc4ced33.jpg)
![20200917185209_1](https://user-images.githubusercontent.com/24946111/93448560-16c82180-f917-11ea-8326-ff04247a9f54.jpg)

**Comment by charliebanks** [comment]
check out v1.3.0 and let me know if all is good

**Comment by Novoca1n3** [comment]
Have installed an still same issue.
![Capture](https://user-images.githubusercontent.com/24946111/94352391-fbdc7680-00a7-11eb-8e6e-95f95014cae5.JPG)
![Capture_1](https://user-images.githubusercontent.com/24946111/94352393-fd0da380-00a7-11eb-9246-4ef65566cae3.JPG)
![Capture1](https://user-images.githubusercontent.com/24946111/94352394-fd0da380-00a7-11eb-9ff4-4752ff7ab8ac.JPG)

**Comment by Novoca1n3** [comment]
Hmm, was just thinking. Maybe I need to import from my save game file as I just opened my saved blender files. Save Game Editor is nerfed due to latest update so I can't test imports

**Comment by Novoca1n3** [comment]
Can confirm all is working. Thank you
