### ISSUE TITLE
The 14 new buildable items from Desolation import as squares

### ISSUE THREAD

**Issue by Novoca1n3** [charliebanks/nms-base-builder#44]
14 new buildable items were added in the Desolation update. These items import into Blender as squares.
![Capture3](https://user-images.githubusercontent.com/24946111/93396437-02eed200-f8bb-11ea-81d1-a0145df797e8.JPG)

**Comment by charliebanks** [comment]
check out v1.3.0 and let me know if all is good

**Comment by Novoca1n3** [comment]
Have installed but still the same issue. Those 3 grey cubes are some of the new items
![Capture](https://user-images.githubusercontent.com/24946111/94352403-229aad00-00a8-11eb-8180-695470c7b8dc.JPG)
![Capture_1](https://user-images.githubusercontent.com/24946111/94352404-23334380-00a8-11eb-9f5d-b41b5f671877.JPG)
![Capture2](https://user-images.githubusercontent.com/24946111/94352405-23cbda00-00a8-11eb-96db-83ddaabfcdcd.JPG)

**Comment by Novoca1n3** [comment]
Hmm, was just thinking. Maybe I need to import from my save game file as I just opened my saved blender files. Save Game Editor is nerfed due to latest update so I can't test imports

**Comment by Novoca1n3** [comment]
Can confirm all is working. Thank you
