### ISSUE TITLE
Blender (beyond 2.80C)  will crash on CTRL+Z Undo After Duplicate Along Curve command

### ISSUE THREAD

**Issue by laanp** [charliebanks/nms-base-builder#47]
Newer releases of Blender (tested on 2.83 LTS & 2.90) will crash if trying to undo "Duplicate Along Curve" NMS plugin command using CTRL + Z.
Blender 2.80C does not have this issue.

**Comment by bjj** [comment]
Probably related: #46

**Comment by charliebanks** [comment]
Are we able to confirm that this is resolved using @bjj fixes with the latest release? :)

**Comment by laanp** [comment]
Hi Charlie,
Confirmed latest release resolves this issue.
Thanks!
