### ISSUE TITLE
Wall Light positions getting garbled using EXPORT NMS

### ISSUE THREAD

**Issue by davebastian** [charliebanks/nms-base-builder#55]
I honestly don't know if this is an issue with the mod or simply a native wall light limitation a/o the sheer number of objects intersecting in such close proximity, but all seems fine in blender until I export the objects--then the positions get garbled.

Before Export (36 parts total)
![NOPE-test-36parts](https://user-images.githubusercontent.com/20446496/96540505-3080bf80-125b-11eb-9dd7-70852b759a1d.jpg)

After Export
![NOPE-test-fail](https://user-images.githubusercontent.com/20446496/96540623-6c1b8980-125b-11eb-837f-957d6988a3f9.jpg)

 I first noticed it when I made a typeface composed of wall lights and added a pangram specimen to a series of walls erected at an existing base in the game. When the result looked like gibberish, I went back to Blender to see if I could remedy the problem there.

Character set + pangram == 630 parts
![volfont-ltd-specimen-blender](https://user-images.githubusercontent.com/20446496/96540697-95d4b080-125b-11eb-8f43-a5e94724a5d1.jpg)

Specimen test BEFORE EXPORT
![specimen-ok](https://user-images.githubusercontent.com/20446496/96540740-b6046f80-125b-11eb-8101-2e68c68a7341.jpg)

Specimen test AFTER EXPORT
![volfont-ltd-specimen-garbled](https://user-images.githubusercontent.com/20446496/96540768-c1579b00-125b-11eb-8da2-a5c92110ce29.jpg)

I tried making the specimen a preset to see if that made nay difference (it didn't).

Preset test BEFORE EXPORT
![specimen-preset-ok](https://user-images.githubusercontent.com/20446496/96540829-e0562d00-125b-11eb-8644-4eb1a84bd92f.jpg)

Preset test AFTER EXPORT
![specimen-preset-garbled](https://user-images.githubusercontent.com/20446496/96540847-f106a300-125b-11eb-9cf6-f439e448b353.jpg)

**Comment by charliebanks** [comment]
Can I see what the transformation data looks like on a wall light? I imagine the text generation tool is introducing some scaling/sheering which I'm not really accounting for in the NMS tool.

If you go to the blender item properties and look for the location, rotation, scale values and pose a screenshot.

Or you can just attach the blender file and I can look inside :)

**Comment by davebastian** [comment]
Bender specimen file attached.
[volfont-ltd-specimen.zip](https://github.com/charliebanks/nms-base-builder/files/5408518/volfont-ltd-specimen.zip)

**Comment by charliebanks** [comment]
> I did change the origin on the first set of lights that were duplicated and then used everywhere else.

This is your problem :) 

Changing the origin basically gives you a misrepresentation of where the object actually is. NMS is only concerned with the origin/transform data to position it's objects. As you've moved the origin to the edge, the objects are going to shift the other way when they are re-imported. The origin information you've changed isn't being tracked by the tool.

**Comment by davebastian** [comment]
I'm a complete Blender newb, but as soon as I posted that I thought maybe that might be the problem. 

Thanks for confirming. 

Back to the drawing board.

**Comment by charliebanks** [comment]
No worries, let me know how it goes! :)

**Comment by davebastian** [comment]
Thanks again for the prompt response.

As it happens, most of the problem was solved by having the culprit revisit the scene of the crime: Set Origin > Origin to Center of Volume (Mass). I applied that, en masse, which placed the origin for each selected light pretty close to where it is natively. I used EXPORT NMS, then turned right around and imported it all back into Blender. That did the trick. I made a few adjustments, then composed some hasty specimens:

![61838-20201021061721962308](https://user-images.githubusercontent.com/20446496/96925012-c0e41d80-1470-11eb-8563-a6bc3eb59e78.png)
![61839-20201021061734026294](https://user-images.githubusercontent.com/20446496/96925018-c2ade100-1470-11eb-943a-890f77f91f9a.png)
![61841-20201021074326680415](https://user-images.githubusercontent.com/20446496/96925000-bd509680-1470-11eb-8f98-71d34eb03c4c.png)

It has warts, but I'm still finessing. I fully intend on contributing some presets once I have something ready.

**Comment by charliebanks** [comment]
Very nice! :)

**Comment by davebastian** [comment]
I would like to become a contributor to No Man's Sky Base Builder Presets
(but could not find another way to message you through GitHub, other than
this).

My github: https://github.com/davebastian

Thanks. That is all.

**Comment by charliebanks** [comment]
Done :)
