### ISSUE TITLE
Mouse Pointer Artifact

### ISSUE THREAD

**Issue by laanp** [charliebanks/nms-base-builder#56]
There appears to be a mouse pointer artifact (4 x "0',s) that shows up in Blender 2.90 or later when performing certain NMS Blender Plugin operations (importing bases, adding new objects from library, etc).
It doesn't affect operations, but changes the mouse pointer until you perform another Blender command or NMS plugin command (but from a Windows interface perspective is an annoyance).

This does not occur in earlier versions of Blender.

![Mouse Pointer Artifact](https://user-images.githubusercontent.com/72280606/96739883-2226c680-1375-11eb-88a9-8b9ff51f16b2.jpg)

**Comment by Devilin-Pixy** [comment]
I believe this is a Blender issue, which has likely been fixed on September 15, 2020 ([T80363](https://developer.blender.org/T80363) and related) for Blender 2.92 experimental.

**Comment by charliebanks** [comment]
Closing due to Blender issue, not plugin issue.
