### ISSUE TITLE
Consider renaming all Operator to remove "nms." namespace

### ISSUE THREAD

**Issue by bjj** [charliebanks/nms-base-builder#61]
It is apparently a limitation of Blender that keyboard shortcuts can only be assigned to Operators in the pre-defined Blender namespace, such as "object" (object mode) or "mesh" (edit mode). You can see the full list in the Blender source, but you can get a general idea by opening settings and looking at the keymap categories.

This applies to manually keymapping in the Settings menu, and it also determines whether the right-click context menu on the operator includes "assign shortcut".

The best compromise is probably to rename everything from "nms.foobar" to "object.nms_foobar"

**Comment by charliebanks** [comment]
Addressed in 1.3.2 :)
