### ISSUE TITLE
Item ID change

### ISSUE THREAD

**Issue by davebastian** [charliebanks/nms-base-builder#65]
Today I discovered that the **Sail Palm** decoration ID has changed from "BASE_HOTPLANT1" to "BASE_HOTPLANT01", which is probably due to a recent game patch. There may be other items that have had their IDs changed, but this is the only one I've verified so far. (The addition of a leading zero would seem to suggest that HG anticipates the addition of more plants to the build menu.)

At any rate, the ID change means that any items with the now-invalid ID won't export to the game, at least not without tweaking the JSON.

**Comment by mswann63** [comment]
I just found this issue too. Looks like it should be a simple change. I think we're due for an update to this amazing tool any way.

**Comment by charliebanks** [comment]
Addressed in 1.3.2 :)
